CONDA_BUILD_SYSROOT: /opt/MacOSX10.10.sdk
blas_impl: mkl
c_compiler: gcc
channel_sources: pytorch-nightly,pytorch,defaults
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: gxx
extend_keys:
- pin_run_as_build
- ignore_build_only_deps
- extend_keys
- ignore_version
fortran_compiler: gfortran
ignore_build_only_deps:
- python
- numpy
lua: '5'
numpy: '1.11'
perl: 5.26.2
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
python: '3.7'
r_base: '3.5'
target_platform: linux-64
vc: '14'
