# This file created by conda-build 3.20.2
# meta.yaml template originally from:
# /root/project/packaging/torchvision, last modified Mon Oct 26 22:38:26 2020
# ------------------------------------------------

package:
    name: torchvision
    version: 0.8.0
source:
    path: /root/project
build:
    script: python setup.py install --single-version-externally-managed --record=record.txt
    script_env:
        - BUILD_VERSION
        - CUDA_HOME
        - FORCE_CUDA
        - NVCC_FLAGS
    string: py37_cu102
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - jpeg 9b h024ee3a_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libpng 1.6.37 hbc83047_0
        - zlib 1.2.11 h7b6447c_3
    host:
        - _libgcc_mutex 0.1 main
        - blas 1.0 mkl
        - ca-certificates 2020.10.14 0
        - certifi 2020.6.20 py37_0
        - cudatoolkit 10.2.89 hfd86e86_1
        - intel-openmp 2020.2 254
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - libuv 1.40.0 h7b6447c_0
        - mkl 2020.2 256
        - mkl-service 2.3.0 py37he904b0f_0
        - mkl_fft 1.2.0 py37h23d657b_0
        - mkl_random 1.1.1 py37h0573a6f_0
        - ncurses 6.2 he6710b0_1
        - ninja 1.10.1 py37hfd86e86_0
        - numpy 1.19.2 py37h54aff64_0
        - numpy-base 1.19.2 py37hfa32c7d_0
        - openssl 1.1.1h h7b6447c_0
        - pip 20.2.4 py37_0
        - python 3.7.9 h7579374_0
        - pytorch 1.7.0 py3.7_cuda10.2.89_cudnn7.6.5_0
        - readline 8.0 h7b6447c_0
        - setuptools 50.3.0 py37hb0f4dca_1
        - six 1.15.0 py_0
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - typing_extensions 3.7.4.3 py_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - cudatoolkit >=10.2,<10.3
        - jpeg
        - libpng
        - numpy >=1.11
        - pillow >=4.1.1
        - python >=3.7,<3.8.0a0
        - pytorch==1.7.0
test:
    imports:
        - torchvision
        - torchvision.datasets
        - torchvision.transforms
    requires:
        - av =8.0.1
        - ca-certificates
        - pytest
        - scipy
    source_files:
        - test
about:
    home: https://github.com/pytorch/vision
    license: BSD
    license_file: LICENSE
    summary: image and video datasets and models for torch deep learning
extra:
    copy_test_source_files: true
    final: true
